Client/ELMS_Client/src/java/model/EmployeeInfoModel.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model;

import java.io.Serializable;

/**
 *
 * @author Mike GTE
 */
public class EmployeeInfoModel implements Serializable {

    public String getEmployeeId() {
        return EmployeeId;
    }

    public void setEmployeeId(String EmployeeId) {
        this.EmployeeId = EmployeeId;
    }

    public String getFirstName() {
        return FirstName;
    }

    public void setFirstName(String FirstName) {
        this.FirstName = FirstName;
    }

    public String getLastName() {
        return LastName;
    }

    public void setLastName(String LastName) {
        this.LastName = LastName;
    }

    public String getPhoneNumber() {
        return PhoneNumber;
    }

    public void setPhoneNumber(String PhoneNumber) {
        this.PhoneNumber = PhoneNumber;
    }

    public int getOrganization() {
        return Organization;
    }

    public void setOrganization(int Organization) {
        this.Organization = Organization;
    }

    public String EmployeeId;
    public String FirstName;
    public String LastName;
    public String PhoneNumber;
    public int Organization;

}

Client/ELMS_Client/src/java/model/LeaveRequestModel.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * @author Mike GTE
 */
public class LeaveRequestModel implements Serializable{
    
    public int EmpId;
    public Date FromDate;
    public Date ToDate;
    public String Reason;

    public int getEmpId() {
        return EmpId;
    }

    public void setEmpId(int EmpId) {
        this.EmpId = EmpId;
    }

    public Date getFromDate() {
        return FromDate;
    }

    public void setFromDate(Date FromDate) {
        this.FromDate = FromDate;
    }

    public Date getToDate() {
        return ToDate;
    }

    public void setToDate(Date ToDate) {
        this.ToDate = ToDate;
    }

    public String getReason() {
        return Reason;
    }

    public void setReason(String Reason) {
        this.Reason = Reason;
    }
    
    
    
}

Client/ELMS_Client/web/view/employee_leave_status.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>Employee Leave Status</title>

        <style>
            body{
                height: 100%;
            }

            .nav-left {
                width: 20%;
            }

            .content {
                width: 79%;
            }
        </style>

    </h:head>
    <h:body>
        <p:layout style="min-width:400px;min-height:200px;">
            <p:layoutUnit position="west" resizable="true" size="200" class="nav-left">
                <p:menu>
                    <p:menuitem value="Home" url="/faces/index.xhtml" icon="ui-icon-home"/>
                    <p:submenu label="RPC Methods">
                        <p:menuitem value="Register Employee" url="/faces/view/employee_registration.xhtml"/>
                        <p:menuitem value="Employee Leave Status" url="/faces/view/employee_leave_status.xhtml"/>

                    </p:submenu>
                    <p:submenu label="RMI Methods">
                        <p:menuitem value="Organization Registration" url="/faces/view/organization_registration.xhtml"/>
                    </p:submenu>
                </p:menu>
            </p:layoutUnit>

            <p:layoutUnit position="center">
                <h:form id="frmEmpLeaveStatusSearch">

                    <p:inputText  id="txtSearch" required="true" value="#{leaveManagementController.empName}" placeholder="Search by Employee Name"/>
                    <p:commandButton id="btnSearch" value="Search" action="#{leaveManagementController.searchEmployeeLeaveInfo()}" update="dtEmpLeaveInfo"></p:commandButton>
                
                    <p:dataTable id="dtEmpLeaveInfo" var="empLeave" value="#{leaveManagementController.employeeLeaveStatus}"
                             paginator="true"
                             paginatorTemplate="{CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                             rowsPerPageTemplate="5,10,15">
                    <p:column headerText="Employee Id">
                        <h:outputText value="#{empLeave.id}" />
                    </p:column>

                    <p:column headerText="Full Name">
                        <h:outputText value="#{empLeave.fullName}" />
                    </p:column>

                    <p:column headerText="Organization">
                        <h:outputText value="#{empLeave.organization}" />
                    </p:column>

                    <p:column headerText="Leave Statu">
                        <h:outputText value="#{empLeave.leaveStatus}" />
                    </p:column>

                    <p:column headerText="Leave Type">
                        <h:outputText value="#{empLeave.leaveType}" />
                    </p:column>

                </p:dataTable>
                </h:form>
            </p:layoutUnit>
        </p:layout>
    </h:body>
</html>

Client/ELMS_Client/web/view/employee_registration.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>Employee Registration</title>

        <style>
            body{
                height: 100%;
            }

            .nav-left {
                width: 35%;
            }

            .content {
                width: 65%;
            }
            
            .input{
                width:500px;
            }
        
        </style>

    </h:head>
    <h:body>
        <p:layout style="min-width:500px;min-height:400px;">
            <p:layoutUnit position="west" resizable="true" size="200" class="nav-left">
                <p:menu>
                    <p:menuitem value="Home" url="/faces/index.xhtml" icon="ui-icon-home"/>
                   
                        <p:menuitem value="Register Employee" url="/faces/view/employee_registration.xhtml"/>
                        <p:menuitem value="Search Employee" url="/faces/view/search_registration.xhtml"/>
                        <p:menuitem value="Organization Registration" url="/faces/view/organization_registration.xhtml"/>
                  
                </p:menu>
            </p:layoutUnit>

            <p:layoutUnit position="center" style="">


                <h:form id="frmEmpRegistration">
                    <p:panelGrid  columns="1">
                        <p:outputLabel id="lblFirstName" value="First Name"/>
                        <p:inputText  id="txtFirstName" required="true" class="input"
                                      value="#{employee.employeeInfo.firstName}"/>
                    </p:panelGrid>

                    <p:panelGrid  columns="1">
                        <p:outputLabel id="lblLastName" value="Last Name"/>
                        <p:inputText  id="txtLastName" required="true" class="input"
                                      value="#{employee.employeeInfo.lastName}"/>
                    </p:panelGrid>

                    <p:panelGrid  columns="1">
                        <p:outputLabel id="lblPhoneNumber" value="Phone Number"/>
                        <p:inputText  id="txtPhoneNumber" required="true" class="input"
                                      value="#{employee.employeeInfo.phoneNumber}"/>
                    </p:panelGrid>


                    <p:panelGrid  columns="1">
                        <p:outputLabel id="lblOrganization" value="Organization"/>
                        <p:inputText  id="txtOrganization" required="true" class="input"
                                      value="#{employee.employeeInfo.organization}"/>
                    </p:panelGrid>

                    <p:commandButton id="btnRegisterEmp" value="Save" action="#{employee.registerEmployee()}" update="frmEmpRegistration"></p:commandButton>
                </h:form>
            </p:layoutUnit>
        </p:layout>
    </h:body>
</html>

Client/ELMS_Client/web/view/manage_leave_type.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>leave Type Management</title>

        <style>
            body{
                height: 100%;
            }

            .nav-left {
                width: 20%;
            }

            .content {
                width: 79%;
            }
        </style>

    </h:head>
    <h:body>
        <p:layout style="min-width:400px;min-height:200px;">
            <p:layoutUnit position="west" resizable="true" size="200" class="nav-left">
                <p:menu>
                    <p:menuitem value="Home" url="/faces/index.xhtml" icon="ui-icon-home"/>
                    <p:submenu label="RPC Methods">
                        <p:menuitem value="Register Employee" url="/faces/view/employee_registration.xhtml"/>
                        <p:menuitem value="Search Employee" url="/faces/view/search_registration.xhtml"/>

                    </p:submenu>
                    <p:submenu label="RMI Methods">
                        <p:menuitem value="Organization Registration" url="/faces/view/organization_registration.xhtml"/>
                    </p:submenu>
                </p:menu>
            </p:layoutUnit>

            <p:layoutUnit position="center">


                <h:form id="frmManageLeaveType">
                    
                    
                    <p:inputText  id="txtLtName" required="true" value="#{leaveManagementController.addLeaveType.name}" placeholder="Leave Type Name"/>
                    <p:inputText  id="txtLtDesc" required="true" value="#{leaveManagementController.addLeaveType.description}" placeholder="Leave Type Description"/>
                    <p:commandButton id="btnAdd" value="Add" action="#{leaveManagementController.addNewLeaveType()}" update="dtLeaveType"></p:commandButton>
                
                    
                    <p:dataTable id="dtLeaveType" var="leaveType" value="#{leaveManagementController.leaveTypes}"
                             paginator="true"
                             paginatorTemplate="{CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                             rowsPerPageTemplate="5,10,15">
                    <p:column headerText="Leave Type Id">
                        <h:outputText value="#{leaveType.id}" />
                    </p:column>

                    <p:column headerText="Name">
                        <h:outputText value="#{leaveType.name}" />
                    </p:column>

                    <p:column headerText="Description">
                        <h:outputText value="#{leaveType.description}" />
                    </p:column>

                    <p:column headerText="Organization">
                        <p:commandButton id="btnRemove" value="Remove" action="#{leaveManagementController.removeLeaveType(leaveType.id)}" update="dtLeaveType"></p:commandButton>
                    </p:column>

                    
                </p:dataTable>
                </h:form>
                
            </p:layoutUnit>
        </p:layout>
    </h:body>
</html>

Client/ELMS_Client/web/view/organization_registration.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>Organization Registration</title>

        <style>
            body{
                height: 100%;
            }

            .nav-left {
                width: 20%;
            }

            .content {
                width: 79%;
            }
        </style>

    </h:head>
    <h:body>
        <p:layout style="min-width:400px;min-height:200px;">
            <p:layoutUnit position="west" resizable="true" size="200" class="nav-left">
                <p:menu>
                    <p:menuitem value="Home" url="/faces/index.xhtml" icon="ui-icon-home"/>
                    <p:submenu label="RPC Methods">
                        <p:menuitem value="Register Employee" url="/faces/view/employee_registration.xhtml"/>
                        <p:menuitem value="Search Employee" url="/faces/view/search_registration.xhtml"/>

                    </p:submenu>
                    <p:submenu label="RMI Methods">
                        <p:menuitem value="Organization Registration" url="/faces/view/organization_registration.xhtml"/>
                    </p:submenu>
                </p:menu>
            </p:layoutUnit>

            <p:layoutUnit position="center">


            </p:layoutUnit>
        </p:layout>
    </h:body>
</html>

Client/ELMS_Client/web/view/request_leave.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>Request Leave</title>

        <style>
            body{
                height: 100%;
            }

            .nav-left {
                width: 20%;
            }

            .content {
                width: 79%;
            }
        </style>

    </h:head>
    <h:body>
        <p:layout style="min-width:400px;min-height:200px;">
            <p:layoutUnit position="west" resizable="true" size="200" class="nav-left">
                <p:menu>
                    <p:menuitem value="Home" url="/faces/index.xhtml" icon="ui-icon-home"/>
                    <p:submenu label="RPC Methods">
                        <p:menuitem value="Register Employee" url="/faces/view/employee_registration.xhtml"/>
                        <p:menuitem value="Search Employee" url="/faces/view/search_registration.xhtml"/>

                    </p:submenu>
                    <p:submenu label="RMI Methods">
                        <p:menuitem value="Organization Registration" url="/faces/view/organization_registration.xhtml"/>
                    </p:submenu>
                </p:menu>
            </p:layoutUnit>

            <p:layoutUnit position="center">
               
                <h:form id="frmRequestLeaave">
                    <p:panelGrid  columns="1">
                        <p:outputLabel id="lblEmployeeId" value="Employee Id"/>
                        <p:inputText  id="txtEmployeeId" required="true"
                                      value="#{leaveManagementController.leaveRequest.empId}"/>
                    </p:panelGrid>

                    <p:panelGrid  columns="1">
                        <p:outputLabel id="lblFromDate" value="From Date"/>
                        <p:calendar id="cldrFromDate" value="#{leaveManagementController.leaveRequest.fromDate}" showOn="button"/>
                        
                    </p:panelGrid>

                    <p:panelGrid  columns="1">
                        <p:outputLabel id="lblToDate" value="To Date"/>
                        <p:calendar id="cldrToDate" value="#{leaveManagementController.leaveRequest.toDate}" showOn="button"/>
                    </p:panelGrid>


                    <p:panelGrid  columns="1">
                        <p:outputLabel id="lblReason" value="Reason"/>
                        <p:inputText  id="txtReason" required="true"
                                      value="#{leaveManagementController.leaveRequest.reason}"/>
                    </p:panelGrid>

                    <p:commandButton id="btnRequest" value="Save" action="#{leaveManagementController.submitRequest()}" update="frmRequestLeaave"></p:commandButton>
                </h:form>
            </p:layoutUnit>
        </p:layout>
    </h:body>
</html>

Client/ELMS_Client/web/view/review_leave_request.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>Employee Leave Status</title>

        <style>
            body{
                height: 100%;
            }

            .nav-left {
                width: 20%;
            }

            .content {
                width: 79%;
            }
        </style>

    </h:head>
    <h:body>
        <p:layout style="min-width:400px;min-height:200px;">
            <p:layoutUnit position="west" resizable="true" size="200" class="nav-left">
                <p:menu>
                    <p:menuitem value="Home" url="/faces/index.xhtml" icon="ui-icon-home"/>
                    <p:submenu label="RPC Methods">
                        <p:menuitem value="Register Employee" url="/faces/view/employee_registration.xhtml"/>
                        <p:menuitem value="Employee Leave Status" url="/faces/view/employee_leave_status.xhtml"/>

                    </p:submenu>
                    <p:submenu label="RMI Methods">
                        <p:menuitem value="Organization Registration" url="/faces/view/organization_registration.xhtml"/>
                    </p:submenu>
                </p:menu>
            </p:layoutUnit>

            <p:layoutUnit position="center">
                <h:form id="frmEmpLeaveStatusSearch">

                    <p:inputText  id="txtSearch" required="true" value="#{leaveManagementController.empName}" placeholder="Search by Employee Name"/>
                    <p:commandButton id="btnSearch" value="Search" action="#{leaveManagementController.searchEmployeeLeaveInfo()}" update="dtEmpLeaveInfo"></p:commandButton>
                
                    <p:dataTable id="dtEmpLeaveInfo" var="empLeave" value="#{leaveRequestManagementController.leaveRequest}"
                             paginator="true"
                             paginatorTemplate="{CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                             rowsPerPageTemplate="5,10,15">
                    <p:column headerText="Employee Id">
                        <h:outputText value="#{empLeave.id}" />
                    </p:column>

                    <p:column headerText="Full Name">
                        <h:outputText value="#{empLeave.fullName}" />
                    </p:column>

                    <p:column headerText="Organization">
                        <h:outputText value="#{empLeave.organization}" />
                    </p:column>

                    <p:column headerText="Leave Statu">
                        <h:outputText value="#{empLeave.leaveStatus}" />
                    </p:column>

                    <p:column headerText="Leave Type">
                        <h:outputText value="#{empLeave.leaveType}" />
                    </p:column>
                        
                        <p:column headerText="&nbsp;">
                            <p:commandButton id="btnSearch" value="Approve" action="#{leaveRequestManagementController.ApproveRequest(empLeave.id)}" update="dtEmpLeaveInfo"/>
                        </p:column>

                </p:dataTable>
                </h:form>
            </p:layoutUnit>
        </p:layout>
    </h:body>
</html>